<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Report extends CI_Model {

	//REPORT CARD
	
	//LIST OF STUDENTS PER SECTION WITH GRADE AT A PERIOD
		
	//LIST OF ADVISEES OF AN ADVISER
		/*(SELECT STUDENT_NAME FROM STUDENT WHERE STUDENT ID=(SELECT STUDENT ID FROM BATCHOF WHERE = (SELECT BATCH ID FROM BATCH WHERE ADVISER_NAME LIKE STUDENT ADVISER)))*/
		
	//LIST OF ALL STUDENTS IN A YEAR WITH GRADE AT A PERIOD
		/*(SELECT STUDENT_NAME, SUBJECT GRADE, GRADING_PERIOD FROM STUDENT, SUBJECT_GRADE WHERE STUDENT ID=(SELECT STUDENT ID FROM BATCHOF WHERE = (SELECT BATCH ID FROM BATCH WHERE STUDENT_YEAR LIKE STUDENT_YEAR))AND GRADING_PERIOD LIKE GRADING_PERIOD AND SUBJECT_ID = SUBJECT_ID)*/

}
